### ISSUE TITLE
_headers not reset on custom error handler?

### ISSUE THREAD

**Issue by ronag** [pillarjs/send#101]
Why is it that `_headers` is set to null when there is no `error` listener while it is not set to null when there is a listener?

https://github.com/BoffinsDev/send/blob/master/index.js#L243

I would like to be able to implement something like this:

```javascript
export default function (basepath) {
  return (req, res, next) => {
    function doSend() {
      send(req, path.join(basepath, req.fileId), { fs: tail })
         // NOTE: https://github.com/pillarjs/send/blob/master/index.js#L242
        .on('error', err => {
          if (err.code === 'ENOENT' || err.statusCode === 404) {
            return next()
          }

          // TODO: https://github.com/BoffinsDev/send/blob/master/index.js#L245
          // if (err.statusCode === 202) {
          //   return setTimeout(doSend, 1000)
          // }

          if (err.statusCode && err.statusCode < 500) {
            return res.sendStatus(err.statusCode)
          }

          return next(err)
        })
        .pipe(res)
    }

    doSend()
  }
}
```

In particular note:

```javascript
if (err.statusCode === 202) {
  return setTimeout(doSend, 1000)
}
```

Where I want to retry sending on 202 errors, see https://github.com/BoffinsDev/send/blob/master/index.js#L563 and later also implement handling of `EAGAIN` from the source stream.

However, that doesn't work because send will complain about headers already being sent, see https://github.com/BoffinsDev/send/blob/master/index.js#L524

**Comment by ronag** [comment]
Related to https://github.com/pillarjs/send/pull/100

**Comment by dougwilson** [comment]
Hi! The reason we do this is to clear all the already-set response headers in Node.js on an error condition. The reason is because the error may occur at any part of the process, and so there may be headers like `ETag` already set that no longer make sense on the error response. If Node.js had a `res.clearHeaders()` API instead, we would of course use that :)
