### ISSUE TITLE
Documented start/end options

### ISSUE THREAD

**Issue by maenu** [pillarjs/send#103]
I wanted to serve only parts of a large file and found the undocumented start/end options to serve exactly this purpose. E.g. I have a large audio file and only want to stream a short extract of which I know the start and end bytes. So I call `/large.mp3?start=1234&end=5678` and pass the query parameters as options to send and I get exactly what I want.
The start and end options are not documented though, therefore I would like to know if this is just missing documentation, or if they are internal properties and setting them might break other features, e.g. conditional-GET etc.

**Comment by dougwilson** [comment]
Hi @maenu, absolutely please feel free to use them. The issue here is just that no one ever documented them. They are definitely part of the public API and we even have tests for those options. I'll leave this issue open until they get documented in the README :)
