### ISSUE TITLE
Option to prefer gz files.

### ISSUE THREAD

**Issue by DylanPiercey** [pillarjs/send#112]
Coming from https://github.com/cloudhead/node-static, they have a "gzip" option that when enabled will automatically serve any .gz files in a directory and fallback to un gzipped variants.

Would it be possible to add a similar option here? I understand that a compression middleware would be most effective in many cases but it would be a handy option to have.

**Comment by dougwilson** [comment]
Are you referring to the progress going on in pull request #108 ?

**Comment by DylanPiercey** [comment]
@dougwilson looks spot on. Thanks for pointing this out.
