### ISSUE TITLE
res.getHeader function does not exist

### ISSUE THREAD

**Issue by basickarl** [pillarjs/send#117]
I'm wondering if this module is not up to date?
```
test.txt
/home/karl/dev/node/proto-buffer-api-karl/node_modules/lasso/node_modules/send/index.js:761
  if (!res.getHeader('Accept-Ranges')) res.setHeader('Accept-Ranges', 'bytes');
           ^

TypeError: res.getHeader is not a function
    at SendStream.setHeader (/home/karl/dev/node/proto-buffer-api-karl/node_modules/lasso/node_modules/send/index.js:761:12)
    at SendStream.send (/home/karl/dev/node/proto-buffer-api-karl/node_modules/lasso/node_modules/send/index.js:531:8)
    at onstat (/home/karl/dev/node/proto-buffer-api-karl/node_modules/lasso/node_modules/send/index.js:624:10)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Express uses the following to set headers: http://expressjs.com/en/4x/api.html
States: `res.set('Content-Type', 'text/html');`. Same goes for koajs.

Can't see any getHeader function either in expressjs nor koajs.

**Comment by dougwilson** [comment]
Express has `.getHeaders`, as it comes from Node.js. Can you provide the following information?

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Complete code I can copy and paste and run to reproduce the issue.
4. Instructions for how I can reproduce the issue.

Thank you!

**Comment by basickarl** [comment]
@dougwilson 
1. Tried both v4.5.0 and v6.6.0
2. ^0.13.0
3 & 4:
 - git clone git@github.com:basickarl/send-error.git
 - cd send-error
 - npm install
 - node index
 - in the browser visit `http://127.0.0.1:3000/static/test.txt`

It's a module called lasso https://github.com/lasso-js/lasso which I'm trying to use. Itself uses send for it's middleware.

**Comment by basickarl** [comment]
I replaced res.getHeader(... with just res.get(... and it seemed to work. Got another error though.

Fair enough nodejs does have it: https://nodejs.org/api/http.html#http_response_getheader_name
Express v4.x doesn't seem to have it: http://expressjs.com/en/api.html#res
Neither does Koajs: http://koajs.com/

**Comment by dougwilson** [comment]
Ah, I see. The `serveStatic` export from `lasso` does not work with `Koa`, which is why you are getting that error. You need to file an issue to make `serveStatic` work with Koa on the lasso module.

>  Express v4.x doesn't seem to have it: http://expressjs.com/en/api.html#res

Not true; At the top of that section, it says:

> The res object is an enhanced version of Node’s own response object and supports all built-in fields and methods.

And Node.js response object (linked to in those docs) has `getHeader` method.

Regardless, the issue is that you're not using lasso correctly, and the error that occurs in this module is just a symptom of that issue.

**Comment by basickarl** [comment]
@dougwilson Ah. I failed to mention that I hav a pull request waiting for the lasso bug with koa: https://github.com/lasso-js/lasso/pull/163

So it does work (with my fix). The next issue if Send now, which is why I started this issue.

**Comment by dougwilson** [comment]
> So what your saying is that send does not support koa?

No, I'm saying that lasso didn't. `send` works just fine with Koa as long as you are actually passing in the correct objects to `send`. They way you were using it was not doing that. The code you showed me, you were passing the Koa context object to his module where you should have been passing in a request object and then you were passing in the Koa next function to this module where you should have been passing in the response object.

**Comment by basickarl** [comment]
@dougwilson Ok gotcha! Just wanted your view on the whole thing!

**Comment by dougwilson** [comment]
No problem, @basickarl I hope that all made sense :)
