### ISSUE TITLE
On a directory, send redirects to the file path plus a slash, not the request URL plus a slash.

### ISSUE THREAD

**Issue by justinfagnani** [pillarjs/send#132]
If `http://127.0.0.1:8081/foo/bar` maps to the directory `/Users/justin/MyProject/foo/bar/`, send redirects to `http://127.0.0.1:8081/Users/justin/MyProject/foo/bar/` and not`http://127.0.0.1:8081/foo/bar/`.

The bug appears to be here https://github.com/pillarjs/send/blob/master/index.js#L675

It seems like it should be:

```javascript
if (stat.isDirectory()) return self.redirect(self.req.originalUrl);
```

**Comment by dougwilson** [comment]
Hi @justinfagnani that can be a mistake in our documentation. You see, the `path` argument is not a file path, but it needs to be the URL path (https://github.com/pillarjs/send#sendreq-path-options) which is what we redirect off if you have not added a `directory` listener to customize the redirection logic.

You can do one of two different things to correct this:

1. Add a `directory` listener and customize how the redirect works to fit your needs (https://github.com/pillarjs/send#serving-from-a-root-directory-with-custom-error-handling is a pretty full example).
2. Just pass in the URL part as the `path` argument and use the `root` option for the rest of the path that is not part of the URL.

I hope that helps!

**Comment by justinfagnani** [comment]
thanks for the quick reply @dougwilson

Regarding the value of `path` - for our case we're remapping URLs to different file paths, so we can't have `path` be a valid URL, and there's no one root that will make URLs map 1-1 to file paths. So we calculate the file path, and use that as the second argument. Works great, except for the redirect problem

I did work around this by defining a `directory` listener, like so:

```javascript
    send(req, filePath)
        .on('directory',
            () => {
              res.statusCode = 301;
              res.setHeader('Location', req.originalUrl + '/');
              res.end('Redirecting to ' + req.originalUrl + '/');
            })
        .pipe(res);
```

But this really seems like it should be the correct default behavior. Other that the default redirect case, users never see `filePath`. Why wouldn't we always want to redirect based on the request URL?

**Comment by dougwilson** [comment]
Hi @justinfagnani my response and closure was around that you are reporting this as a bug, when it is functioning as designed and you're currently using it for something it was never designed for. If you would like to re-phrase this as a feature request, please feel free to open a new issue (or way, way better: a PR) that outlines (or codifies) a proposal for how you would like the module to behave and outline your use-case so we can have a discussion around the proposal :)

When you made this issue, you simply said it was a bug, but it's not: it is designed to work this way, and was never designed to accept full file paths as the `path` argument.
