### ISSUE TITLE
How do I send a file when I only have its actual file-system path but not its urlencoded path?

### ISSUE THREAD

**Issue by UlyssesAlves** [pillarjs/send#138]
I've read in docs the following passage:

> The req is the Node.js HTTP request and the path is a urlencoded path to send (urlencoded, not the actual file-system path).

I have a doubt on how I should implement this. I have created a server to stream audio files (_without send package yet_) to HTML5 enabled browsers, and the audio control is requesting ranges of my streamed file. The audio starts playing succesfully, but the problem is that eventually, after some minutes of playing I got the error net:ERR_CONTENT_LENGHT_MISMATCH, and that's why I've decided to look for a package to do this streaming job for me. So that's how I got here on send package's repository.

Now I didn't understand that section I quoted above. Do I have to implement two endpoints? One which serves the full file in some kind of an urlencoded path and another that servers the same file as a stream with send package? Then I would pass the first endpoints urlencoded path as an argument to the send package's endpoint, which in turn would perform the ranged streamming of the file for me?

Sorry, but it's a bit confusing for me. I just need a simple explanation or small example of how I could use send package to send my files through their file-system paths. That would be very helpfull. 

Thanks very much.

**Comment by dougwilson** [comment]
Hi @UlyssesAlves what the docs are trying to convey is that the `path` argument needs to be urlencoded (aka percent encoded) and not the decoded form. This means that if you already have a raw file system path, simply run it through `encodeURI()` to get the value you would pass into this module.

**Comment by UlyssesAlves** [comment]
OK, @dougwilson. Thanks for the answer. I don't remenber now that I'm away from my computer, but I think I've used another solution for this. FileServer or something like that. Anyway, closing the issue.
