### ISSUE TITLE
Make the request optional

### ISSUE THREAD

**Issue by matthewp** [pillarjs/send#143]
When using an H2 server you might want to PUSH some stuff, like images. These won't have requests. It would be great if the request param was optional so you can use send in this scenario.

**Comment by dougwilson** [comment]
Yea, that could be doable. What would need to change in this module? Just looking through all the uses of `req` in the library here, it would basically cut out the majority of what this module does, pretty much leaving you with just `fs.createWriteStream(fileName).pipe(res)`, which seems like something you could just perform manually, no?

**Comment by matthewp** [comment]
Yeah, the more I dug into it the more I felt the same.  You also depend on a Response which is different from what you get with the H2 pushStream API. So I think this can be closed.

Really all you need is to convert a URL to a file path, which is why I thought to use `send`. But I'm sure there are many other npm modules which can do this part (I haven't found one yet though).

**Comment by dougwilson** [comment]
You may be able to use https://www.npmjs.com/package/resolve-path for that purpose. The bottom example is how this module does path resolution. This module will change to just use `resolve-path` with the next major (there is a slight difference right now).
