### ISSUE TITLE
Regular Expression Denial of Service in mime 1.4.0

### ISSUE THREAD

**Issue by StanFisher** [pillarjs/send#144]
According to NSP, there is a regular expression denial of service in one of your dependencies. The mime package needs to be updated to either version 1.4.1 or greater than or equal to 2.0.3.

This is rated as a high severity by Node Security Platform.

https://nodesecurity.io/advisories/535

**Comment by dougwilson** [comment]
A fix will be released Monday Oct 6 (see statement at https://github.com/expressjs/express/issues/3431). The dependency may have an issue, but the issue does not impact this module. There is no patch available for the dependency without a semver-minor change, so we cannot simply release a patch version of this module.

**Comment by dougwilson** [comment]
I would love to update it earlier as a patch if you know a method in which we can achieve a semver-patch upgrade of the dependency that has the fix.

**Comment by dougwilson** [comment]
Right now `master` is staging a semver-minor release of this module. I'm talking about bumping from the current-published version of 1.3.4.

**Comment by dougwilson** [comment]
Sorry, it's hard to describe anything now. I'm getting multiple emails a minute now about this before I had a change to do anything. Now my hands are basically being tied, unable to perform any code / releases / help and instead endlessly replying to emails.
