### ISSUE TITLE
[Security] Update mime

### ISSUE THREAD

**Issue by yashha** [pillarjs/send#150]
https://github.com/nuxt/nuxt.js/issues/2074

**Comment by yashha** [comment]
Hm should be fixed with mime >= 1.4.1

**Comment by yashha** [comment]
Nevermind :)
https://snyk.io/vuln/npm:mime:20170907

**Comment by dougwilson** [comment]
There is no issue with tge current version of this module as it uses mime 1.4.1 You can read that 1.4.1 is safe in the advisory: https://snyk.io/vuln/npm:mime:20170907 as 1.4.1 was released specifically to backport the security fix to the 1.x line.

**Comment by yashha** [comment]
Yo sorry for that, that's why I closed it,

**Comment by dougwilson** [comment]
Yea, sorry, there was a bunch of emails closed then reopened etc so wasn't sure if it was about to be opened again so wanted to comment. Sometimes people will close and reopen 4 times to get attention to their issue so this was looking the same pattern.
