### ISSUE TITLE
Update Mime >= 2.0.3

### ISSUE THREAD

**Issue by bryanCoteChang** [pillarjs/send#152]
Current version of Mime is vulnerable according to the Node Security Platform: https://nodesecurity.io/advisories/535

Please update to version 2.0.3.  I attempted to create a branch and do it myself, but I do not think I have the permission to do so.

Thank you!

**Comment by dougwilson** [comment]
Hi @bryanCoteChang you can see the vulnerable versions at the top of the advisory you linked to:

> Vulnerable: < 1.4.1 || > 2.0.0 < 2.0.3
> Patched: >= 1.4.1 < 2.0.0 || >= 2.0.3

We are using a patched version with the latest version of send already: version 1.4.1 (which was specifically released just to include that patch).

**Comment by bryanCoteChang** [comment]
Ah wow, I suck I see now sorry.  It's another package using an older version of send that is the issue, not an issue with the latest version of send.  Thank you for the clarification!
