### ISSUE TITLE
RangeNotSatisfiableError: Range Not Satisfiable

### ISSUE THREAD

**Issue by PassTheMayo** [pillarjs/send#153]
Hello. I am currently running an Express server with Pug render engine. I recently got this error from the `send` module:

![image](https://user-images.githubusercontent.com/16949253/34062202-ececf212-e1b0-11e7-8e73-8e60d2593e39.png)

I do not know what this means, or how I got it. Any help?

EDIT: I just realized I am getting this from several other services that I am running that uses Express and Pug. I'm guessing this has to do with requests in Express?

**Comment by dougwilson** [comment]
The error means that a request asked for a range that was outside the size of the file requested and so a Range Not Satisfiable had to be sent back as the response to that request as per HTTP rules.

**Comment by PassTheMayo** [comment]
Do you know which module gave me this error besides `send`? @dougwilson

**Comment by dougwilson** [comment]
I don't really know based on the information provided, unfortunately. If you could provide code to run and a way to reproduce I can connect a debugger and trace through it for you.

**Comment by PassTheMayo** [comment]
@dougwilson I do not know what triggered this, or how I received it. I have no file uploading within any of the services that I use, so could there be another reason?

**Comment by dougwilson** [comment]
Well, the error means that a request asked for a range that was outside the size of the file requested and so a Range Not Satisfiable had to be sent back as the response to that request as per HTTP rules. I wouldn't know what request or what file based on the info so far. If you log all your requests in an access log style, look for ones with the response code 416.

**Comment by PassTheMayo** [comment]
@dougwilson Nothing seemed to be in my Nginx access logs or error logs that had `416` in it. Still a mystery...

**Comment by dougwilson** [comment]
Maybe you could add a custom error hander to your app and log some extra information when you get that error? That would be probably the next step to figure out why it happens.

**Comment by PassTheMayo** [comment]
True, thanks, I'll try it out when I get the time. For now I'll close this.

**Comment by dougwilson** [comment]
Ok. Let me know what you find! We can always reopen this issue too.

**Comment by zekageri** [comment]
I recently got this error.

When i upload some really large videos into a folder, the js client will refresh the contents on the web when they are uploaded.
The video on the client side has this line in the src: `#t=0.1`, So the client tries to load the first picture of the video.

It looks like when the video is uploaded, the file system is not ready to serve it yet and i got this error:

```JS
RangeNotSatisfiableError: Range Not Satisfiable
node_modules\send\index.js:725:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
node:internal/validators:92
      throw new ERR_OUT_OF_RANGE(name, `>= ${min} && <= ${max}`, value);
      ^

RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 2147483647. Received 3636863719
    at Object.write (node:fs:817:5)
    at WriteStream._write (node:internal/fs/streams:395:13)
    at doWrite (node:internal/streams/writable:408:12)
    at clearBuffer (node:internal/streams/writable:569:7)
    at WriteStream.<anonymous> (node:internal/streams/writable:262:7)
    at Object.onceWrapper (node:events:513:28)
    at WriteStream.emit (node:events:394:28)
    at emitConstructNT (node:internal/streams/destroy:301:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {     
  code: 'ERR_OUT_OF_RANGE'
}
[nodemon] app crashed - waiting for file changes before starting..
```

The upload is done with `require("express-fileupload");`

**with this snippet:**

```JS
file.mv(`${path}/${file.name}`,function(err){
    if(err){
        res.status(400).json({status: "error", message: `${file.name} upload error!`});
    }else{
        res.status(200).json({status: "success", message: `${file.name} upload success!`});
    }
});
```
