### ISSUE TITLE
mime package upgrade

### ISSUE THREAD

**Issue by airgun2062** [pillarjs/send#163]
Hi,
mime ^2.0 does not have lookup() and charsets. Instead use getType() or getExtension() ?
Errors in line 839, 846
https://www.npmjs.com/package/mime

Thanks,
Arjun

**Comment by dougwilson** [comment]
This modules requires `mime` 1.x, as in the dependencies. The `mime` 1.x is still maintained with the old API. There are no plans to upgrade to `mime` 2.x at this time as it will require Node.js >= 6.
