### ISSUE TITLE
fs.stat() is failing - Precondition Failed

### ISSUE THREAD

**Issue by barintsights** [pillarjs/send#169]
Hi,

I have an issue that pops through expressjs, by the function that catches the uncaught errors:

```Javascript
app.use(
    (err, req, res, next) => { ... } 
);
```

By serving an static files, one of them is 4 MB video A.K.A `bg.mp4`, and it being served very well, until sometimes (rarely) i get this unexpected error:

```Javascript
GET /static/img/bg.mp4
Precondition Failed
PreconditionFailedError: Precondition Failed at SendStream.error (/home/bar/proj/src/node_modules/send/index.js:270:31) at SendStream.send (/home/bar/proj/src/node_modules/send/index.js:633:12) at onstat (/home/bar/proj/src/node_modules/send/index.js:730:10) at FSReqWrap.oncomplete (fs.js:153:5)
```

I did try to google for this issue back and forth, but there aren't common issues, so this is kinda my last hope.

Thanks!

**Comment by dougwilson** [comment]
The title says the stat is failing, but the stack trace doesn't seem to indicate that. Are you sure the request that had that error didn't send a precondition?

**Comment by barintsights** [comment]
@dougwilson Lightning speed reply :astonished: , The title based on the error message that says `Precondition Failed` , but the stack error is giving some extra details. unfortunately i don't have any info about the failed request, only from the thrown error itself.

**Comment by dougwilson** [comment]
Gotcha. I mean, I just don't see anything to indicate an issue here. It would seem to me that the client is sending a precondition test in the request which fails. A precondition is contained in the "If-Match" or "If-Unmodified-Since" request headers.

**Comment by dougwilson** [comment]
I'm going to close this for now since it's been a month.
