### ISSUE TITLE
Question: headers already sent issue

### ISSUE THREAD

**Issue by amitguptagwl** [pillarjs/send#170]
I'm working on a web framework and facing an issue as the headers are already sent. So I just want to understand the purpose of the following line:
```javascript
this.setHeader(path, stat)
```
https://github.com/pillarjs/send/blob/master/index.js#L624

**Comment by r0mflip** [comment]
As I understand [this method](https://github.com/pillarjs/send/blob/ea926ba28b9e058fb67d24f883a8ce1680f7b883/index.js#L860) is what will be called where the stats are used to set headers like `Cache-Control` and `ETag`, and it also emits the headers.

**Comment by amitguptagwl** [comment]
Hmm. shouldn't it be optional? I mean based on some configuration. In addition, is it not possible to set it when the stream is being returned to pipe instead of setting when sending.

**Comment by amitguptagwl** [comment]
Yes. But what my concern is it should be set while returning the stream, not at the time of sending the stream to the client.

**Comment by amitguptagwl** [comment]
Some web frameworks including [mine](https://github.com/node-muneem/muneem) send the headers before the data/stream. 

```js
res.writeHeaders( statusCode, headers);
someStream.pipe( res );
```

Now when I use this library to send some file to the client

```js
var someStream = send(req, path, { root: "/root/folder" });
res.writeHeaders( statusCode, headers);
someStream.pipe( res );//Error: headers are already sent
```

So I'm supposed to change the code

```js
var someStream = send(req, path, { root: "/root/folder" });

res.statusCode = statusCode;
var headersName = Object.keys( headers );
for(let i=0; i< headersName.length; i++){
    res.setHeader( headersName[i],  headers[ headersName[i] ]);
}

someStream.pipe( res );//Error: headers are already sent
```

In my opinion, relevant headers should have been set on the first line in the above code when you return the SendStream.

**Comment by dougwilson** [comment]
Thanks for the information! I'm not familiar with your framework, so not sure what is happening. Usually to help would either need (a) a pull request with a fix or (b) code and instructions to reproduce so we can debug it and come up with a fix.

**Comment by amitguptagwl** [comment]
Ah! I believe I failed to highlight the issue. Code in above comment is not related to any framework. Let me convert them in steps;

**Step 1** : send a file to client
```
var someStream = fs.createReadStream( "/root/folder/path" );
res.writeHeaders( statusCode, headers);
someStream.pipe( res );
```

**Step 2** : send a file to client using send library.
```
var someStream = send(req, path, { root: "/root/folder" });
res.writeHeaders( statusCode, headers);
someStream.pipe( res ); //Error: headers are already sent
``` 

I've no problem in raising the PR. But in my opinion, the issue should be cleared and agreed to be fixed.

**Comment by dougwilson** [comment]
Ah. Yea, the error is because the header was already written out before you called the .pipe method on the object returned by this module. You can of course turn off though the options of this module all those headers that are trying to be set (or set them before calling .pipe since we won't overwrite them), but of course you'll still have issues when this module tries to write out redirects or error responses unless you override those behaviors too.

**Comment by amitguptagwl** [comment]
ok. So I'm considering that fixing this library to set the header while returning the SendStream is not the appropriate solution.
