### ISSUE TITLE
progress event

### ISSUE THREAD

**Issue by karmac2015** [pillarjs/send#175]
Is there a way to detect the progress status for send file ?

**Comment by karmac2015** [comment]
I solve it now by registering the stream event then register data event for stream event like the following:
```
send(...)
.on('stream', stream => {
  stream.on('data', chunk=> {
      // calculate progress here
  })
})
.pipe(...)
```

**Comment by dougwilson** [comment]
Ah, yea, I was going to suggest something similar, but that has one main issue: I think that registering on a stream data listener may turn off the back pressure feature of Node.js, which can balloon your app's memory usage. It would also be the progress read of your local fs, and not the progress of sending to the end client.

**Comment by karmac2015** [comment]
So how can I do that? please help me

**Comment by dougwilson** [comment]
Just looking at progress-stream module I don't think it's possible to work without adding some new support to it to support progress on http responses from server pov.

**Comment by dougwilson** [comment]
I don't know the solution, or I would have posted already :) and now I'm on mobile phone, so cannot try anything out until perhaps tomorrow at the earliest.

**Comment by karmac2015** [comment]
Ok thank you, but please one last question if I use [through2](https://www.npmjs.com/package/through2) library so pipe data to the library then pipe it to response it has an effect on the back pressure like registering data event for stream ?

**Comment by dougwilson** [comment]
I'm not familiar with the through2 lib, so would need some time to learn it and test it and get the answer for you.

**Comment by karmac2015** [comment]
Ok thank you very much

**Comment by karmac2015** [comment]
Hello, is there any solution till now ?

**Comment by dougwilson** [comment]
I'm going to close this as stale. Unless Node.js adds some kind of progress events to the fs streams, it is probably not possible.

**Comment by hello-smile6** [comment]
> I'm going to close this as stale. Unless Node.js adds some kind of progress events to the fs streams, it is probably not possible.

Then why not open an issue for Node?

**Comment by dougwilson** [comment]
Because to open a feature request in Node.js, you need to also champain it and even implement it yourself as a pull request if you cannot convince a maintainer to do it. You can read more about how feature requests work in their guidelines. I have no bandwidth to do such a thing, unfortunately.

But anyone who does is welcome to do so.
