### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by evgeny-nadymov** [pillarjs/send#180]
Could you please update npm package in order to use latest mime-types? Compilation streaming support for wasm module requires right mime type to be returned. But Send npm package is used by Express and it returns wrong mime type currently. It seems that this issue has already been resolved at source code. I will be really appreciate for updated npm package.

**Comment by evgeny-nadymov** [comment]
Could you please update npm package in order to use latest mime-types?

**Comment by dougwilson** [comment]
This module does not use the mime-types module as a dependency. 

The included types are only the defaults. If you need a type, just define it: https://github.com/pillarjs/send/blob/master/README.md#custom-file-types

Releases of this module occur in lock with Express releases. The Express 4.17 release is being worked on and a new send will be released soon to go along with it.

**Comment by SgSridhar** [comment]
The current mime version is at `2.4.4`, but the mime version is locked to `1.6.0`. Could you please upgrade the version to the latest? Because of few business reasons, we would like to have few core deps (at least the one with major updates) to keep closer to the latest. Is that something feasible?
