### ISSUE TITLE
regex vuln in debug

### ISSUE THREAD

**Issue by YOU54F** [pillarjs/send#185]
Hi,

You may wish to upgrade debug . - see [here](https://github.com/visionmedia/debug/issues/501)

```
              └─ send:0.17.1
                    └─ debug:2.6.9
```

```
Vulnerabilities

DepShield reports that this application's usage of debug:2.6.9 results in the following vulnerability(s):

(CVSS 7.5) CWE-400: Uncontrolled Resource Consumption ('Resource Exhaustion')
Occurrences

debug:2.6.9 is a transitive dependency introduced by the following direct dependency(s):

• @pact-foundation/pact:8.2.4
        └─ @pact-foundation/pact-node:8.3.3
              └─ caporal:1.2.0
                    └─ tabtab:2.2.2
                          └─ debug:2.6.9
              └─ sumchecker:2.0.2
                    └─ debug:2.6.9
        └─ body-parser:1.19.0
              └─ debug:2.6.9
        └─ express:4.17.1
              └─ debug:2.6.9
              └─ finalhandler:1.1.2
                    └─ debug:2.6.9
              └─ send:0.17.1
                    └─ debug:2.6.9

• lint-staged:8.1.6
        └─ micromatch:3.1.10
              └─ extglob:2.0.4
                    └─ expand-brackets:2.1.4
                          └─ debug:2.6.9
              └─ snapdragon:0.8.2
                    └─ debug:2.6.9
```

**Comment by dougwilson** [comment]
Whatever scanner you used has the wrong versions. The issue you linked to has the fix backported to debug 2.6.9, which is what we are using.

**Comment by YOU54F** [comment]
Cheers @dougwilson for the reply, I am sorry for the multiple issues across the repos I have opened then.

I will raise an issue with depshield as it keeps raising false positives and I'm sure it is time consuming for maintainers, contributors and the OSS community in general.

Keep up the good work!

**Comment by dougwilson** [comment]
Hey! It's no problem. I saw they were security so wanted to look into it asap. I saw it was an old issue and saw it was the one I had the debug project backport to 2.x series thankfully :) The link you provided was a big help.

I think a lot of the scanners just put simple ranges without going into backport details sadly. I actually haven't heard of DepShield before. I wonder what their source is.

**Comment by YOU54F** [comment]
Cheers buddy, glad to help. It is disappointing, as I was pleased when Depshield was announced, I thought it would be really good, but I think it has caught 3 genuine issues out of the 127 it has raised on my various repos.

I've now uninstalled it and sent a tweet to them, telling them off for wasting everyones time, as false positive security alerts only tend to lead people to ignore all of them and miss the genuine one.

Great work on getting them to backport the fix too! Now that is why I <3 OSS!

PS. btw much respect for express!!! hero
