### ISSUE TITLE
control size of partial content (206)

### ISSUE THREAD

**Issue by mhf-ir** [pillarjs/send#196]
Any method for control chunk of partial content.
It's good practice for CND usage.

Or even better start with 206 for file larger than 8m 

one of the main concept of HLS/Dash is each file could be cache on CDN/Cache Servers also seek during video will be easy without load Start to Seek position.

**Comment by dougwilson** [comment]
Hi, thanks for the issue. I'm really not sure what you are asking, unfortunately. Are you able to provide more specifics or even a pull request demonstrating what you are looking for?

**Comment by r0mflip** [comment]
@mhf-ir AFIK HLS and DASH don't use range requests and they usually format individual chunks of size 1MB. You can see a damo at https://players.akamai.com/players/hlsjs It doesn't use any range requests at all to give a partial content. As for your question, `send` does seem to support partial content responses (https://github.com/pillarjs/send/blob/master/index.js#L675-L687). This can be done by `range` header which IIRC all modern browers do for large files.

**Comment by mhf-ir** [comment]
> @mhf-ir AFIK HLS and DASH don't use range requests and they usually format individual chunks of size 1MB. You can see a damo at https://players.akamai.com/players/hlsjs It doesn't use any range requests at all to give a partial content. As for your question, `send` does seem to support partial content responses (https://github.com/pillarjs/send/blob/master/index.js#L675-L687). This can be done by `range` header which IIRC all modern browers do for large files.

I know hls and dash chunk files all files response 200 not 206.
Partial content is good for great Largfile with single request.

Consider this senario
```
First request for get file 1GB:
Browser send request to webserver
Web server tell client/browser your file is about **1GB** but take this chunk for example this **8mb**
Browser request again for next **8mb** ... and server give it to client.
Each request could be cached via CDN server if chunk always stick to special number.
```
https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/#slice
https://www.nginx.com/blog/smart-efficient-byte-range-caching-nginx/

**Comment by r0mflip** [comment]
@mhf-ir Are you saying that when a client requests the server for a huge file (not an explicit range request), the server should send a partial content back to the client?

**Comment by dougwilson** [comment]
This module already allows you to chunk files inder the 200 response code with the `start` and `end` options. If this does not work, please provide some specific details and reasons why and we can reopen this issue. It is still generally unclear what the request is.
