### ISSUE TITLE
Please upgrade mime version

### ISSUE THREAD

**Issue by Nstd** [pillarjs/send#211]
Current mime version is 1.6.0，but mime ^2.0.0 has breaking change, hope to upgrade it.
My dependency path: `@vue/cli-service 5.0.4 > webpack-dev-server ^4.7.3 > express 4.17.3 > serve-static  1.14.2 > send 0.17.2 > mime 1.6.0`

**Comment by dougwilson** [comment]
Hi @Nstd the version of mime cannot be upgraded in send 0.x, as it is not backwards-compatible. You can preview the next major version of send 1.0.0-beta.1 which is published to npm, if you like. This no longer has the old mime dependency.

**Comment by Nstd** [comment]
> Hi @Nstd the version of mime cannot be upgraded in send 0.x, as it is not backwards-compatible. You can preview the next major version of send 1.0.0-beta.1 which is published to npm, if you like. This no longer has the old mime dependency.

@dougwilson Thanks for your reply, but I'm not directly use `send` in my project. I just use the newest `mime` library, only the previous dependencies upgrade to the newest version when your v1.0.0 is released, that can fix my problem. Hope it will be released soon. Thanks~

**Comment by dougwilson** [comment]
Hi @Nstd no problem. The new version is already published to npm. I unfortunately cannot control when modules that use this module change their version. If you can only take action when a module you are using directly makes some kind of change, then I would recommend opening an issue there rather than here.

**Comment by Nstd** [comment]
@dougwilson Thanks for your suggestion. I check that the express has released [5.0.0-beta.1](https://www.npmjs.com/package/express/v/5.0.0-beta.1) which depends on the newest `send`, but mybe it's only a beta version, so the `webpack-dev-serve` not upgrade their dependencies.
