### ISSUE TITLE
Move to pillarjs org?

### ISSUE THREAD

**Issue by dougwilson** [pillarjs/send#72]
/cc @tj @jonathanong

**Comment by jonathanong** [comment]
ask @tj to move it but yes, i agree

**Comment by dougwilson** [comment]
I cc'd him here, just in case :) Apparently I cannot connect AppVeyor to this repo since I don't have enough privileges.

**Comment by jonathanong** [comment]
...why appveyor?

**Comment by dougwilson** [comment]
Mainly, because this module does a lot of file system path manipulation. At least, I work on Windows, so I catch issues that slip by where a change works on Linux but fails on Windows. I'd like to just have the tests include Windows, so PRs can have the same insight.

**Comment by jonathanong** [comment]
does it completely replace travis or whatever or does it augment it?

**Comment by dougwilson** [comment]
You can think of it as "Travis CI for Windows"; since it doesn't so Linux, it's a supplement :)
