### ISSUE TITLE
How would you send a single local HTML file?

### ISSUE THREAD

**Issue by binarykitchen** [pillarjs/send#76]
I have a gulp-connect task here and am looking for a middleware that enables me to send just one local HTML file, depending on the URL.

How would you do this with this module?

**Comment by dougwilson** [comment]
It doesn't get much simpler than the readme:
```js
app.use(function (req, res, next) {
  send(req, encodeURI('/path/to/fle.html')).pipe(res)
})
```

**Comment by binarykitchen** [comment]
or even better without any dependency:

```js
fs.createReadStream("index.html").pipe(res)
```

**Comment by dougwilson** [comment]
The question you asked was how to use this module...
