### ISSUE TITLE
emit('end') when notModified()

### ISSUE THREAD

**Issue by kiliwalk** [pillarjs/send#84]
i have an use case that need to know the `SendStream` is end all the time. Might add this feature? i can push a pull request

**Comment by dougwilson** [comment]
The end event is purposely only emitted when a stream is actually sent, so unfortunately no, we wouldn't accept this, as it would break a current feature.

If you want to know when the response is finished, you can listen to the finish event that res emits. Would that work? If not, can you describe your exact use-case you are trying to achieve?

**Comment by dougwilson** [comment]
Sorry, didn't mean to close.

**Comment by kiliwalk** [comment]
yes, i know the `end` event's meaning for the stream. the response's finish event is effective, with just a longer event loop. and i was wondering whether the response will emit error after SendStream is end, so that the finish event on the resp will not be emitted. 
so, for the general logic and consistency, if i listen the error event of SendStream, i should listen its corresponding end event too, not other's end event.

the use case is that:
i use [fibers](https://www.npmjs.com/package/fibers) to make the request processing run in sequence/sync. while the send stream pipes, the fiber stack is waited and i need to resume it on error or end.
see [the code](https://github.com/kiliwalk/tier/blob/master/middlewares/static.js#L37)

**Comment by dougwilson** [comment]
Ah. Sounds like if you use the on-finished module on res, it will handle all those cases you are looking to (just like we do in this module to ensure the file descriptor is cleaned up).

**Comment by dougwilson** [comment]
onFinished(resp, function () { fiber.resume(); }):

Should ensure the fiber is resumed in all cases, including errors.

**Comment by dougwilson** [comment]
The onFinished callback may give an error as the first argument as well, so probably want to handle that too :)

**Comment by kiliwalk** [comment]
thanks, i will try it

**Comment by dougwilson** [comment]
BTW your module looks really neat :) Let me know if the on-finished module is not working or any other question and I can play around with your module if you need help porting middlewares or anything :)

**Comment by kiliwalk** [comment]
thanks for your appreciate. yeah, my module is just simple, and i want to make the node-coding simple too. 
i tried your advice, but i have to bind the end/error event to both send stream and response finally. now it's fine and safe, though might not clearly.
thanks all the same:)
