### ISSUE TITLE
Add pending HTTP methods

### ISSUE THREAD

**Issue by piranna** [pillarjs/send#85]
Add the remaining main HTTP methods (POST, PUT, PATCH and DELETE). I know these would need some special security considerations, so I'm not sure if they should (or could!) be implemented on an external module...

**Comment by dougwilson** [comment]
Hi! This is a good idea, but probably left to a different module. The module's name itself is "send", which is to imply it's main functionality: sending files (as responses), rather than receiving them.

You could always use this module for the sending part of the larger file CRUD module :)

**Comment by piranna** [comment]
So [here you have your module](https://github.com/piranna/recv) :-) Probably needs more work, but it's a good start :-D I've build it as a middleware since it seemed more easy to do...
