### ISSUE TITLE
actual treatment of dotfiles and dotdirs

### ISSUE THREAD

**Issue by coolaj86** [pillarjs/send#91]
This is the actual treatment of docfiles, which differs slightly from the documentation

**default**:

* **200**: http://example.com/.hidden/foo
* **404**: http://example.com/.hidden/.dot
* **200**: http://example.com/.hidden/.deep/foo
* **404**: http://example.com/.hidden/.deep/.dot

`ignore`:

* **404**: http://example.com/.hidden/foo
* **404**: http://example.com/.hidden/.dot
* **404**: http://example.com/.hidden/.deep/foo
* **404**: http://example.com/.hidden/.deep/.dot

`allow`:

* **200**: http://example.com/.hidden/foo
* **200**: http://example.com/.hidden/.dot
* **200**: http://example.com/.hidden/.deep/foo
* **200**: http://example.com/.hidden/.deep/.dot

`deny`:

* **403**: http://example.com/.hidden/foo
* **404**: http://example.com/.hidden/.dot
* **403**: http://example.com/.hidden/.deep/foo
* **404**: http://example.com/.hidden/.deep/.dot

**Comment by dougwilson** [comment]
> which differs slightly from the documentation

Can you be more specific?

**Comment by coolaj86** [comment]
Intuitively (and others may feel differently) I would expect this behavior:

* `undefined`: console.warn('[deprecated] please specify opts.dotfiles') and support legacy to not break code
* `true` or `'allow'`: no special treatment
* `false` or `'deny'`: 403 all dotfiles and 403 dotdirs
* `['.allow-me', '.me-too']`: allow these specific dotfiles / dotfolders
* ``[]` or 'ignore'`: 404 all dotfiles and 404 dotdirs

**Comment by dougwilson** [comment]
>  undefined: console.warn('[deprecated] please specify opts.dotfiles') and support legacy to not break code

It's not deprecated, thus why there is no warning. Now sure why we'd want to deprecate this.

**Comment by dougwilson** [comment]
For your `deny` example, I get 403 for all 4 cases you provided above. Can you please share your code so I can reproduce? They should all be 403 and they all are for me.

**Comment by coolaj86** [comment]
The code says it's `legacy`: https://github.com/pillarjs/send/blob/master/index.js#L108

When I hear `legacy` I think "we wish we had done it differently, but it is how it is" which I further translate to: "let's deprecate and remove this in the next major version" - which is what express itself has done several times.

I would like to show you my code, unfortunately it is not in a state that I can currently share. But I'll look into it more and when I have something I can share I'll let you have it.

I'll also update to the latest version of send. I'm on `0.12.2`, not `0.13`

**Comment by dougwilson** [comment]
Hi @coolaj86 , "legacy" does not meant we have any intention to deprecate something--writing in a comment that it's deprecated would. We would never deprecate something unless there was an alternative. We also have the `deprecate()` function to use to warn people, which we would have easily used if the functionality was deprecated, just like all that other deprecated functionality.

> which is what express itself has done several times.

If you have any specific references, that would be awesome :) I'm the only person working on Express and I don't remember ever equating legacy as deprecated there :)

> I would like to show you my code, unfortunately it is not in a state that I can currently share. But I'll look into it more and when I have something I can share I'll let you have it.


Ok. Until then, please, just make pull requests to us if you cannot provide a way to reproduce. Typically in cases like this when you don't provide us any way to replicate or a fix, we try to read & understand your description and reproduce with it. If unsuccessful, we provide you the exact steps we used to reproduce and ask you to at least try to build on it to provide a reproduction.

Ultimately without us being able to reproduce or you offering up a fix, there is nothing we can do. We can't fix something we don't understand or can see :)

> I'll also update to the latest version of send. I'm on 0.12.2, not 0.13

I wouldn't expect any of this functionality to be different between the two versions.

**Comment by dougwilson** [comment]
I'm going to close this issue, as we have the pull request regarding the documentation changes you are looking to make and I think I have anything else that was in here covered. Let me know if I missed something in here or need to re-open.

**Comment by dougwilson** [comment]
For your discrepancy in the `deny` example above, I attempted to look into it, but wasn't able to reproduce. We didn't have tests for it, so I added them in https://github.com/pillarjs/send/commit/f84f3bc73ebdb6be8d93eaf1830be9393f51ec6b and they passed at https://travis-ci.org/pillarjs/send/builds/96407806

If you think there is something to look into there, please let me know and provide me with a fix or some code to reproduce :) I'm always happy to fix a bug, but it's hard without being able to reproduce.
