### ISSUE TITLE
Use _Accept_ header to guess the content type

### ISSUE THREAD

**Issue by felicienfrancois** [pillarjs/send#96]
The `content-type` response header should be guessed from both the file type (guessed from extension and/or content) AND from the `Accept` request header.

Uses cases:
- files without extension
- unknown files extension
- text files that could be use in different ways: either displayed or processed using javascript or downloaded.

**Comment by dougwilson** [comment]
Hi! I've never heard a standard for this before. Can you point me to a standard that specifies what the steps would be, how to resolve multiple types in the `Accept` header, etc.? If there is not a standard, I'm not sure if it really belongs in this module, especially since you should be able to easily implement this by yourself using the `headers` event (https://github.com/pillarjs/send#events):
```js
send(req, req.url)
.on('headers', guessContentType)
.pipe(res)

function guessContentType(res, path, stat) {
  var req = res.req
  // perform your logic here and eventually...
  res.setHeader('Content-Type', guessedType)
}
```

**Comment by felicienfrancois** [comment]
The `Accept` Header is a HTTP 1.1 standard header, one of the header used for content negociation.
Here the official spec https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1
Here a more readable doc: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation

This header is used by the browser or any agent to indicate what content is _acceptable_ by the client
The spec indicate that the server _may_ use it for content negociation and specify in a quite clear way how this header _should_ be interpreted by the server.

> content negotiation is the mechanism that is used, when facing the ability to serve several equivalent contents for a given URI, to provide the best suited one to the final user

the served content means response body AND headers. The most signifant one is `Content-Type`

Practically, the `Accept` header is set in all major browser to indicate to the server how will be used the resource (i.e. what content type is acceptable) and the `Content-Type` header is used by all major browsers to determine how to use the served content.

In most cases, the content-type header does not prevent the browser the use it in the way it want (for example an img tag seems to be always displayed as an image, ignoring the content-type header).
But when the browser does not know how to use the response, this creates unwanted behaviors. This could be the case when:
- typing an url in the address bar
- loading a resource in an iframe
- preloading resources using javascript

For example, files without extension (or with an unhandled extension like .php) served by send are currently triggering a download.

Regarding send, the Accept header should be at least used:
- to guess the content-type when the content type is not guessable from the file extension
- to determine the content-type to use when there are several content type guessed from the file extension

**Comment by dougwilson** [comment]
Hi! Sorry if I was not clear. What I was asking for a standard for is regarding

> to guess the content-type when the content type is not guessable from the file extension

Can you be more specific on the exact algorithm that we should use to do this? Is there a standard out there that defines this algorithm? The listed standard you provided does not, as far as I can tell. It only outlines an idea. For example, the `Accept` header contains many different types by most web browsers. How should this module select which one to use? What if the accept header is just `Accept: */*`? We cannot send back `Content-Type: */*` because that is not a valid type. I'm just asking for the algorithm to use to make this determination.

> to determine the content-type to use when there are several content type guessed from the file extension

Currently, we don't have any way to do this, because internally, the module we use only gives a 1-to-1 mapping of file extension to type. If you have any ideas around how to accomplish this, that would be welcome!

A big concern that comes to my mind with this feature is security. For example, for users who allow uploads and use this module to serve them up. As an example, a site only allows image files, so accepts only uploads with `.jpg` or `.jpeg` extensions. Then, that image is served up by this module. Well, a malicious user uploads HTML with JavaScript with a file extension of `.jpg`. With the current code, it will contain `Content-Type: image/jpeg`. From the sounds of this change, if that malicious user know a web browser sends the header `Accept: text/html, application/javascript, text/xml, */*;q=0.6`, they would reference that `.jpg` file and this module would instead send back `Content-Type: text/html`, since that looks like what the browser wants. Now, malicious script is running on that domain, which is a persistent XSS attack scenario. What would we need to do to help mitigate against this with this feature?

**Comment by felicienfrancois** [comment]
> to guess the content-type when the content type is not guessable from the file extension

I just have enquired a bit deeper. There are no standard for this but Apache HTTPD server implements it quite simply, with a one to one mime types map.
The main differences with the actual implementation of send are:
- There is no default content type (the header is not set if not guessed. (Before 2.2.7 the default content type was `text/plain` in order to not trigger download)
- The guessed content type is passed through their [content negociation algorithm](http://httpd.apache.org/docs/2.2/en/content-negotiation.html#algorithm) which may result in a 406 Error if the guessed content type is not acceptable (i.e. `Accept` header does not contains `*/*` and the guessed content type does not match any of the acceptable types)

__In a nutshell__:
- The issue of wierd behavior (triggering download or so) should be preferably fixed by not setting a default `content-type` header
- The Accept header could be handled to improve send but in a filtering way (I don't see any added value to this ...)

**Comment by dougwilson** [comment]
Can you work on putting a pull request together?

**Comment by dougwilson** [comment]
> Before 2.2.7 the default content type was text/plain in order to not trigger download

Are you sure you are not confusing this module with something else? There has never been a version 2.2.7 of this module; we have not even reached 1.0.0

**Comment by felicienfrancois** [comment]
> Are you sure you are not confusing this module with something else? There has never been a version 2.2.7 of this module; we have not even reached 1.0.0

Sorry if I wasn't clear, I was talking about apache. Default mime type of apache httpd was [text/plain in 2.2.x](http://httpd.apache.org/docs/2.2/mod/core.html#defaulttype). In [current release, there is no default content type](http://httpd.apache.org/docs/current/mod/core.html#defaulttype), In this case the client have to determine itself how to use this undetermined content.

> Can you work on putting a pull request together?

Yes, I'll have a look at the code and make a pull request.
But the discussion may not be over ...
Not setting the content-type header may be a breaking changes for some people, in case they asume it is always set and do tests on it, without testing its existence (I mean in the server side, in a later response filter, like gzip encoding for example).
What do you think about?
What is the send module policy about possibly breaking changes? is a version bump + a warning note enough or should we implement it in several steps
1. adding a defaultType setting which is recommended to be set to null but has a default to `text/plain` (or the the old default of send which seems to be application/octet-stream). We may also print a warning to console if the setting is not set.
2. Then switch later the default to null (and remove the recommendation & warnings)

**Comment by felicienfrancois** [comment]
I've just made a pull request: https://github.com/pillarjs/send/pull/97

**Comment by dougwilson** [comment]
Hi @felicienfrancois,

> Not setting the content-type header may be a breaking changes for some people, in case they asume it is always set and do tests on it, without testing its existence (I mean in the server side, in a later response filter, like gzip encoding for example).
> What do you think about?

Well, I'm not going to accept that into this module, I'm sorry. You may want to consider forking if you really want that behavior. A response with an entity body should always have a `Content-Type` header, at the very least to prevent the very persistent XXS attack I highlighted above, which I don't think you addressed/responded to.

>  What is the send module policy about possibly breaking changes? is a version bump + a warning note enough or should we implement it in several steps

Well, the policy right now is to implement it in a backwards-compatible way, if at all possible (perhaps that means the functionality have to be opt-in). Then use deprecation that we have to get people to change their code in such a way that they can get rid of the deprecation without changing the behavior of their existing code & make upgrading to the next major a non-issue.

As far as timing for another major, that is dependent upon the timeline of the Express project, as this project will not bump to 1.0 until Express bumps it's major version. Any pull request that targets the next major of this module should be made against the https://github.com/pillarjs/send/tree/1.x branch.

> I've just made a pull request: #97

I see nothing in that pull request regarding the use of the `Accept` header, so as far as I can tell, that is not even related to the discussion here regarding the use of the `Accept` header?

**Comment by felicienfrancois** [comment]
> I see nothing in that pull request regarding the use of the Accept header, so as far as I can tell, that is not even related to the discussion here regarding the use of the Accept header?

Yes your right, as I pointed out, this header is mostly used for not static contents or multiple static contents served on the same URI, which is not the case in send.
In the case of pure `one URI = one file` static servers, it may be used to check if the served content is acceptable and send a 406 error if not.
This could theorically be useful to prevent some XSS attacks (for example if the `Accept` header was equal to `image/jpeg, image/*`, it would mean it only accept images and serving a .html file should result a 406 error instead).
But all modern browsers append `*/*` to the `Accept` header for all kind of requests, so the served content is always acceptable.
=> Implementing such a filter in send could be done but has no added value

So this issue can be closed.
I will open a new issue regarding the default Content-Type header
