### ISSUE TITLE
Default content type

### ISSUE THREAD

**Issue by felicienfrancois** [pillarjs/send#98]
Discussion forked from #96
Related to Pull request #97

Currently, when the mime type could not be determined from the file extension (unknown extension or no extension), the `Content-Type` header is set to `application/octet-stream` (the default of [mime module](https://github.com/broofa/node-mime))
`application/octet-stream` is not a neutral content-type, in some cases it may trigger download (and possibly execution).

It should be:
- Changed to either `text/plain` or no `Content-Type` header
- Documented
- Tweakable through options

**Comment by felicienfrancois** [comment]
@dougwilson

# Always have a Content-Type header ?

> A response with an entity body should always have a Content-Type header

Can you point me out to this rule and its justification ? Apache Httpd and other security aware http servers default to no `Content-Type` header.

> A response with an entity body should always have a Content-Type header, at the very least to prevent the very persistent XXS attack I highlighted above, which I don't think you addressed/responded to.

We're talking about the case where the mime type could not be resolved so the file path has no extension or an unknown extension. So either the file was not renamed after upload (too bad, I can also upload .html files) or it as been explicitly renamed with a bad extension (or no extension).
So this may introduce a XSS security breach if all thoose conditions are met:
- files content is not checked after upload
- files not processed after upload (no image resize or whatever)
- files are uploaded with no processing (no image resize or whatever)
- files ARE renamed, but without extension or with an unknown one (typo?)
- files are displayed widely (i.e. not just for the one who uploaded)
- files are displayed using a way where `Content-Type` header is not ignored by browsers (for example src of iframe)

1- Hopefully, this case is rare
2- It is so badly designed that it may be full of other security breach
3- Is it the role of send to prevent XSS attack on such XSS friendly design?

# Security concerns

As I said, the default `application/octet-stream` content-type is not neutral, it trigger download when `Content-Type` header is not ignored.
On top of being an unwanted behavior in most cases, this is a security issue.
It may allow to makes people download virus and malwares without them knowing it (depending on the browser/download manager, the download could be hardly noticeable).
Some OS/browser combination may also execute it or propose to execute it.

`application/octet-stream` is a bad default content type. If we want to stick with a default `Content-Type` header (for security concerns or backward compatibility), the safe one is `text/plain` (prevent html from being executed).
This was the default of Apache httpd 2.2 (now it is No Content-Type header).

# Backward compatibility

> Well, the policy right now is to implement it in a backwards-compatible way, if at all possible (perhaps that means the functionality have to be opt-in). Then use deprecation that we have to get people to change their code in such a way that they can get rid of the deprecation without changing the behavior of their existing code & make upgrading to the next major a non-issue.

I propose to:
- add a `defaultType` option in master branch (minor update) which default to either `text/plain` (should not be a breaking change, but this is may have impact) or `application/octet-stream` (if you want no change at all)
- set the default to No `Content-Type` header (if you're OK with that) or to `text/plain`

Related deprecation notices, I don't know what is the good way to do it.

**Comment by dougwilson** [comment]
Ah, OK, I understand your current request. So, here's the thing: we simply use the `node-mime` library to lookup MIME types. How it decides the defaults is up to this library, and we even expose a reference to this library as the `.mime` export, so you can configure it.

So, to me, this means the following:

1. We need to fix the bug where we throw an exception if you set that's module's default type to `null`, and instead we need to just not produce a `Content-Type` header in that case.
2. You'll need to bring your argument of the default to that module, and depending on how the change is resolved, we'll just end up puling in the change.

**Comment by felicienfrancois** [comment]
Thank you for your answer and the fix. I will pull this idea to the mime repository
